---
# tasks file for while_true_do.srv_pcp

- name: Manage pcp Packages
  package:
    name: "{{ wtd_srv_pcp_package }}"
    state: "{{ wtd_srv_pcp_package_state }}"
  become: true
  tags:
    - pcp
    - package

- name: Manage pcp-pmda-* Packages
  package:
    name: "{{ wtd_srv_pcp_package_pmda }}"
    state: "{{ wtd_srv_pcp_package_state }}"
  become: true
  when: wtd_srv_pcp_package_pmda
  tags:
    - pcp
    - package

- name: Manage pcp Services
  service:
    name: "{{ item }}"
    state: "{{ wtd_srv_pcp_service_state }}"
    enabled: "{{ wtd_srv_pcp_service_enabled }}"
  become: true
  register: pcp_srv_state
  retries: 3
  delay: 10
  until: pcp_srv_state is success
  loop: "{{ wtd_srv_pcp_service }}"
  when:
    - wtd_srv_pcp_package_state != "absent"
  tags:
    - pcp
    - service

- name: Configure /etc/sysconfig/pmcd
  template:
    src: "sysconfig.pmcd.j2"
    dest: "/etc/sysconfig/pmcd"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  notify: Restart pmcd
  when:
    - wtd_srv_pcp_package_state != "absent"
  tags:
    - pcp
    - configuration

- name: Configure /etc/pcp/pmlogger/control.d/*
  template:
    src: "pmlogger.control.d.j2"
    dest: "/etc/pcp/pmlogger/control.d/{{ item.name }}"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  notify: Restart pmlogger
  loop: "{{ wtd_srv_pcp_conf_pmlogger_control_d }}"
  when:
    - wtd_srv_pcp_package_state != "absent"
  tags:
    - pcp
    - configuration
