---
# tasks file for while_true_do.srv_pcp

- name: Gather package facts
  package_facts:
    manager: auto
  tags:
    - pcp
    - facts
    - package

- name: Manage pcp Dependencies
  package:
    name: "procps-ng"
    state: "present"
  become: true
  when:
    - wtd_srv_pcp_package_state != "absent"
  tags:
    - pcp
    - package

- name: Manage pcp Packages
  package:
    name: "{{ wtd_srv_pcp_package }}"
    state: "{{ wtd_srv_pcp_package_state }}"
  become: true
  tags:
    - pcp
    - package
    - monitoring

- name: Manage pcp-pmda-* Packages
  package:
    name: "{{ wtd_srv_pcp_package_pmda }}"
    state: "{{ wtd_srv_pcp_package_state }}"
  become: true
  loop: "{{ wtd_srv_pcp_package_pmda }}"
  when:
    - wtd_srv_pcp_package_state != "absent"
  tags:
    - pcp
    - package
    - monitoring

- name: Configure /etc/sysconfig/pmcd
  template:
    src: "sysconfig.pmcd.j2"
    dest: "/etc/sysconfig/pmcd"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  notify: Restart pmcd
  when:
    - wtd_srv_pcp_package_state != "absent"
  tags:
    - pcp
    - configuration
    - monitoring

- name: Configure /etc/pcp/pmlogger/control.d/*
  template:
    src: "pmlogger.control.d.j2"
    dest: "/etc/pcp/pmlogger/control.d/{{ item.name }}"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  notify: Restart pmlogger
  loop: "{{ wtd_srv_pcp_conf_pmlogger_control_d }}"
  when:
    - wtd_srv_pcp_package_state != "absent"
  tags:
    - pcp
    - configuration
    - monitoring

- name: Manage pcp Services
  service:
    name: "{{ item }}"
    state: "{{ wtd_srv_pcp_service_state }}"
    enabled: "{{ wtd_srv_pcp_service_enabled }}"
  become: true
  loop: "{{ wtd_srv_pcp_service }}"
  when:
    - wtd_srv_pcp_package_state != "absent"
  tags:
    - pcp
    - service
    - monitoring

- name: Manage pcp Firewalld Service
  firewalld:
    service: "{{ wtd_srv_pcp_fw_service }}"
    state: "{{ wtd_srv_pcp_fw_service_state }}"
    immediate: true
    permanent: true
    zone: "{{ wtd_srv_pcp_fw_service_zone }}"
  become: true
  when:
    - '"firewalld" in packages'
    - wtd_srv_pcp_fw_mgmt
    - wtd_srv_pcp_conf_pmcd_local == "1"
  tags:
    - pcp
    - configuration
    - firewall
    - security
