---
# handlers file for while_true_do.srv_pcp

- name: Restart pmcd
  service:
    name: pmcd
    state: restarted
  become: true
  tags:
    - pcp
    - service
    - monitoring

- name: Restart pmlogger
  service:
    name: pmlogger
    state: restarted
  become: true
  tags:
    - pcp
    - service
    - monitoring
