---
# handlers file for while_true_do.srv_pcp

- name: Restart pmcd
  service:
    name: pmcd
    state: restarted
  register: pmcd_srv_state
  retries: 5
  delay: 5
  until: pmcd_srv_state is success
  become: true
  tags:
    - pcp
    - service

- name: Restart pmlogger
  service:
    name: pmlogger
    state: restarted
  register: pmlogger_srv_state
  retries: 5
  delay: 5
  until: pmlogger_srv_state is success
  become: true
  tags:
    - pcp
    - service
