---
# handlers file for while_true_do.srv_pcp

- name: Restart pmcd
  service:
    name: pmcd
    state: restarted
  retries: 3
  delay: 10
  become: yes
  tags:
    - pcp
    - service

- name: Restart pmlogger
  service:
    name: pmlogger
    state: restarted
  retries: 3
  delay: 10
  become: yes
  tags:
    - pcp
    - service
