---
- name: Converge
  hosts: all
  roles:
    - role: while_true_do.srv_pcp
      wtd_srv_pcp_conf_pmcd_local: 0
      wtd_srv_pcp_conf_pmlogger_control_d:
        - name: "labrat01"
          host: "labrat01.wtd.local"
